# Generated by Django 5.2.1 on 2025-05-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_id", models.IntegerField()),
                ("day_title", models.CharField(max_length=200)),
                ("duration", models.IntegerField()),
                ("completed_date", models.DateTimeField(auto_now_add=True)),
                ("completed_exercises", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-completed_date"],
            },
        ),
    ]
